# Site
repository: happywangmakeit/happywangmakeit.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Xiaole Wang
title: Undergraduate student of Peking University
email: wangxiaole0401@gmail.com
website: www.github.com/happywangmakeit

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  happywangmakeit
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hi, my name's Xiaole Wang(王效乐) and I'm a sophomore student majoring in Intelligent science and technology(and a double major in economics) at Peking University. 
 
 Now my research interest mainly fall in <mark>Quantitative trading</mark> and <mark>Computer vision</mark>, and I'm also interested in other cutting-edge technology in AI field! 

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/happywangmakeit
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  happywangmakeit/happywangmakeit
  #           icon: fab fa-github
  #           url: github.com/happywangmakeit/happywangmakeit.github.io
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wangxuan institute of Computer Science
        link: https://deepvideolab.top/
        link_text: deepvideolab
        sub_title: Intern Student
        caption: March 2024 - Present
        quote: >
          Deep-video Lab
        description: | # this will include new lines to allow paragraphs
          I'm working as Professor Sun Jun's intern in Deep-video Lab. My research direction is <mark>Quantative</mark> and I'm a beginner for it.
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Peking University
        caption: 2021 - Present
        sub_title: Intelligent science and technology(with a double major in economics)
        quote: >
          Established in 1898
        description: | # this will include new lines to allow paragraphs
          2022.10 - 2023.6 Minister of Life Department of Peking University Student Union
          
          2022.6 - 2023.6 Minister of Public Relations, Student Union, School of Government Management
          
          National Encouragement Scholarship, Peking University third-class Scholarship, Peking University Merit student and other awards。

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     # Look at this cool image  
  #     # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
